# Generated by Django 6.0.4 on 2026-05-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cancion',
            new_name='Libro',
        ),
    ]
